INHERIT: mkdocs.yml
plugins:
  - meta
  - blog:
      post_url_date_format: yyyy
      post_url_format: "{slug}"
      # archive: false
      categories: false
  - tags
nav:
  - Blog:
    - blog/index.md