[tool.poetry]
name = "cleanrl"
version = "0.5.0"
description = "High-quality single file implementation of Deep Reinforcement Learning algorithms with research-friendly features"
authors = ["Costa Huang <costa.huang@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^1.9.0"

tensorboard = "^2.5.0"
wandb = "0.12.1"
pyglet = "^1.5.19"
opencv-python = "^4.5.3"
gym = {git = "https://github.com/openai/gym.git"}

# Atari-related dependencies
ale-py = {version = "^0.7", optional = true}
AutoROM = {version = "^0.3.1", optional = true}
stable-baselines3 = {version = "^1.1.0", optional = true}

# Pybullet-related dependencies
pybullet = {version = "^3.1.8", optional = true}

[tool.poetry.dev-dependencies]
spyder = "^5.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
atari = ["ale-py", "AutoROM", "stable-baselines3"]
pybullet = ["pybullet"]



